version: '3'
services:
  fastapi:
    container_name: test_fastapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - test-app
networks:
  test-app:
    driver: bridge
